"""Known MCP servers with their tools for quick selection."""

from .models import MCPServerConfig, MCPConnectionType

KNOWN_MCP_SERVERS = [
    MCPServerConfig(
        name="filesystem",
        description="Read and write files on the local filesystem",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-filesystem", "/tmp"],
        tool_filter=["read_file", "write_file", "list_directory", "create_directory", 
                     "move_file", "search_files", "get_file_info"],
    ),
    MCPServerConfig(
        name="github",
        description="Interact with GitHub repositories",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-github"],
        env={"GITHUB_PERSONAL_ACCESS_TOKEN": ""},
        tool_filter=["create_or_update_file", "search_repositories", "create_repository",
                     "get_file_contents", "push_files", "create_issue", "create_pull_request",
                     "fork_repository", "create_branch", "list_commits", "list_issues"],
    ),
    MCPServerConfig(
        name="notion",
        description="Read and write Notion pages and databases",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@notionhq/notion-mcp-server"],
        env={"OPENAPI_MCP_HEADERS": '{"Authorization": "Bearer YOUR_TOKEN", "Notion-Version": "2022-06-28"}'},
        tool_filter=["notion_retrieve_page", "notion_query_database", "notion_create_page",
                     "notion_update_page", "notion_search", "notion_create_database",
                     "notion_retrieve_comments", "notion_add_comment"],
    ),
    MCPServerConfig(
        name="kubernetes",
        description="Interact with Kubernetes clusters",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@anthropics/mcp-kubernetes"],
        tool_filter=["kubectl", "get_pods", "get_logs", "describe_resource", "get_events",
                     "get_namespaces", "get_deployments", "get_services"],
    ),
    MCPServerConfig(
        name="slack",
        description="Send messages and interact with Slack",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-slack"],
        env={"SLACK_BOT_TOKEN": "", "SLACK_TEAM_ID": ""},
        tool_filter=["slack_post_message", "slack_reply_to_thread", "slack_add_reaction",
                     "slack_get_channel_history", "slack_get_thread_replies",
                     "slack_list_channels", "slack_get_users"],
    ),
    MCPServerConfig(
        name="puppeteer",
        description="Browser automation and web scraping",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-puppeteer"],
        tool_filter=["puppeteer_navigate", "puppeteer_screenshot", "puppeteer_click",
                     "puppeteer_fill", "puppeteer_select", "puppeteer_hover",
                     "puppeteer_evaluate"],
    ),
    MCPServerConfig(
        name="postgres",
        description="Query PostgreSQL databases",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-postgres"],
        env={"POSTGRES_CONNECTION_STRING": ""},
        tool_filter=["query", "list_tables", "describe_table"],
    ),
    MCPServerConfig(
        name="sqlite",
        description="Query SQLite databases",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "/tmp/db.sqlite"],
        tool_filter=["read_query", "write_query", "create_table", "list_tables", 
                     "describe_table", "append_insight"],
    ),
    MCPServerConfig(
        name="brave-search",
        description="Search the web using Brave Search",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@anthropics/mcp-brave-search"],
        env={"BRAVE_API_KEY": ""},
        tool_filter=["brave_web_search", "brave_local_search"],
    ),
    MCPServerConfig(
        name="google-maps",
        description="Search for places and get directions",
        connection_type=MCPConnectionType.STDIO,
        command="npx",
        args=["-y", "@anthropics/mcp-google-maps"],
        env={"GOOGLE_MAPS_API_KEY": ""},
        tool_filter=["maps_geocode", "maps_reverse_geocode", "maps_search_places",
                     "maps_place_details", "maps_distance_matrix", "maps_directions",
                     "maps_elevation"],
    ),
]

BUILTIN_TOOLS = [
    {"name": "google_search", "description": "Search Google for information"},
    {"name": "exit_loop", "description": "Exit a LoopAgent loop"},
    {"name": "load_memory", "description": "Load memories from the memory service"},
    {"name": "load_artifacts", "description": "Load artifacts from the artifact service"},
    {"name": "preload_memory", "description": "Preload memory into context"},
    {"name": "transfer_to_agent", "description": "Transfer control to another agent"},
    {"name": "url_context", "description": "Fetch and include URL content"},
]

